export_languages: [
  "fr"
]
files:
  - source: /sys/src/sample.json
    translation: /%original_path%/%two_letters_code%-%original_file_name%
    excluded_target_languages: [
      "en",
      "fr"
    ]
