project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /sys/src/**/*.json
    ignore:
      - /sys/src/**/fr-*.json
      - /sys/src/**/uk-*.json
    translation: /external/**/%two_letters_code%-%original_file_name%
    languages_mapping:
      two_letters_code:
        "en-UD": "Something_Else"
